### PR TITLE
Added animations across the rest of the page sections

### PR DESCRIPTION
**Pull request by ekfuhrmann**
## About
This PR extends animation to the other sections through use of a simple data attribute and `batch` feature of ScrollTrigger. As the content is brought into view it's batched and then animated in based on the attribute directives.

### CODE REVIEW

**Comment by ekfuhrmann** [comment]
I'm thinking about killing the animation replaying on scroll-up and subsequent scroll-downs. I might swap it to only load once and then persist with the exception being only for the case studies. What do you guys think?

**Comment by andrewmosby** [comment]
> I'm thinking about killing the animation replaying on scroll-up and subsequent scroll-downs. I might swap it to only load once and then persist with the exception being only for the case studies. What do you guys think?

Yeah I'd say once it animates in, don't kill it and animate back, especially since there's already animation on scroll after it animates in with the parallax items. Not animating back and forth might also make it a little more performant in addition to being a better user experience.

**Comment by andrewmosby** [comment]
Also, considering the title, I'll add that I think normal text links should also have a slight animation. Whether the underline gets slightly thicker and changes color (along w/ text color) or maybe the underline offsets down a touch.... just something subtle since there's so much activity on the page it shouldn't be crazy IMO.

**Comment by ekfuhrmann** [comment]
I'm going to spin up a PR that doesn't re-animate for comparison that we can check out. I'll be interested to see if the page feels more performant, though I think most of the initial chugging is due to the volume of image assets being used. I _hope_ a CDN might help alleviate that a bit. I'm sure @jeremyfrank will have some more insight there when he's back.

**Comment by andrewmosby** [comment]
I was thinking about that as well, and since all of those images are split apart, there's also a lot of requests. I don't think _that_ would cause jittery animations, though.

**Comment by andrewmosby** [comment]
Perhaps b/c it's animating so much with opacity? Can you try to make only one fire at a time (even if scroll goes quickly)? If that smooths it out a bit, we can come up w/ a solution based on that.

**Comment by ekfuhrmann** [comment]
That's an interesting idea. [GSAP has some ways of managing the batch](https://gsap.com/docs/v3/Plugins/ScrollTrigger/static.batch()#configuration) that should help with this, namely providing a `batchMax` which allows me to limit how much is coming in at any given time. You might be on to something, but I worry that may create a pseudo choppiness as it batches pieces out differently.

[I also spun up a page that only animates content once](https://deploy-preview-14--viget-startups.netlify.app/). I like it for the core sections, but sort of like the case studies themselves animating back in still. Lots to play around with here though to see what feels best.

**Comment by ekfuhrmann** [comment]
Made a bunch of adjustments here. Specifically, I've now only got the triggers firing once which seems to be helping with the general speed of the page. I also adjusted the duration of the animation, speeding it up slightly, which make it feel smoother, and then I also found tweaking the animations themselves seems to be helping. Reducing the amount of motion running concurrently, unsurprisingly helps with the general speed.

**Comment by andrewmosby** [comment]
I am partial to them staying on the page once they've animated in since there's still some movement anyhow. Maybe get some other opinions, though.

**Comment by jeremyfrank** [comment]
+1 to just animating things in once and locking them in place (no re-animating out/in with each scroll).

I didn't review the original animation PR so this is more feedback about the animations in general, and it's also subjective so feel free to do with it what you want. HMU when you want to chat performance, I have some ideas I can run past you.

Can we set the point at which each panel animation starts to be higher up into the viewport? When I scroll at a slow to average speed, the animation starts off-screen near the bottom and I don't get to see most of it. Making them start higher up would resolve this since they'd be fully on-screen. However this would be problematic for fast scrolling, causing the animation to happen _too_ high in the viewport. Maybe a variable velocity based start point is the answer to that? I'm not sure if or how this would be possible w/ Gsap.

Also I'd suggest animating _less_ in the content panels below the 4 main case studies:

* Why work with us? – I'd make this all static since it's secondary supporting content.
* Design and develop – Maybe make the heading and lead text static, and animate the graphic and left/right text.
* What our clients say – I'd make this static as well since it's secondary supporting content.
* Client logos – The scrolling is good, but I don't think they need to fade in or scale up if the text above is made to be static.

**Comment by ekfuhrmann** [comment]
Merging this in as it's in a pretty stable state right now. I'm going to be doing some more performance tweaks in a follow-up PR.

**Pull request merged**
